
List<MyProductModel> myProductModel = [
  MyProductModel(
    image: 'food-delivery(foodel)/ramen/laptop1.png',
    name: 'MacBook Air M2',
    price: 2241.86,
    rate: 4.9,
    distance: 997,
    description: "Ультралёгкий ноутбук от Apple с мощным чипом M2 и отличной автономностью.",
    category: "Laptop",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/ramen/laptop2.png',
    name: 'Dell XPS 13',
    price: 2473.77,
    rate: 4.2,
    distance: 353,
    description: "Компактный ноутбук премиум-класса с высоким разрешением экрана и стильным дизайном.",
    category: "Laptop",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/ramen/laptop3.png',
    name: 'HP Spectre x360',
    price: 2113.89,
    rate: 4.6,
    distance: 949,
    description: "Трансформируемый ноутбук с сенсорным экраном и высоким уровнем производительности.",
    category: "Laptop",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/ramen/laptop4.png',
    name: 'Asus ROG Zephyrus',
    price: 645.01,
    rate: 4.3,
    distance: 163,
    description: "Игровой ноутбук с высокой производительностью и эффективным охлаждением.",
    category: "Laptop",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/ramen/laptop5.png',
    name: 'Lenovo ThinkPad X1',
    price: 2181.55,
    rate: 4.7,
    distance: 889,
    description: "Бизнес-ноутбук с прочной сборкой и высоким уровнем безопасности данных.",
    category: "Laptop",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/burger/phone1.png',
    name: 'iPhone 15 Pro',
    price: 2047.99,
    rate: 3.8,
    distance: 795,
    description: "Флагманский смартфон от Apple с улучшенной камерой и A17 Pro чипом.",
    category: "Phone",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/burger/phone1.png',
    name: 'Samsung Galaxy S24',
    price: 2256.21,
    rate: 4.6,
    distance: 201,
    description: "Новейший Android-смартфон с Dynamic AMOLED 2X дисплеем и топовой камерой.",
    category: "Phone",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/burger/phone1.png',
    name: 'Google Pixel 8',
    price: 524.02,
    rate: 4.8,
    distance: 778,
    description: "Смартфон с чистым Android и лучшей в классе вычислительной фотографией.",
    category: "Phone",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/burger/phone1.png',
    name: 'OnePlus 12',
    price: 2415.77,
    rate: 4.7,
    distance: 878,
    description: "Флагман с быстрым зарядом, производительным процессором и плавным интерфейсом.",
    category: "Phone",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/burger/phone1.png',
    name: 'Xiaomi 13 Pro',
    price: 2232.76,
    rate: 4.1,
    distance: 445,
    description: "Смартфон с флагманской камерой Leica и отличным соотношением цена/качество.",
    category: "Phone",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/tablet/tablet1.png',
    name: 'iPad Pro M2',
    price: 787.99,
    rate: 3.6,
    distance: 255,
    description: "Планшет с мощностью ноутбука, дисплеем Liquid Retina и поддержкой Apple Pencil.",
    category: "Tablet",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/tablet/tablet1.png',
    name: 'Samsung Galaxy Tab S9',
    price: 1973.42,
    rate: 5.0,
    distance: 522,
    description: "Флагманский Android-планшет с AMOLED-экраном и стилусом S Pen.",
    category: "Tablet",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/tablet/tablet1.png',
    name: 'Xiaomi Pad 6',
    price: 1487.60,
    rate: 4.0,
    distance: 240,
    description: "Доступный планшет с хорошей производительностью и большим экраном.",
    category: "Tablet",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/tablet/tablet1.png',
    name: 'Lenovo Tab P11',
    price: 972.52,
    rate: 4.4,
    distance: 845,
    description: "Планшет среднего класса с высоким качеством изображения и стереодинамиками.",
    category: "Tablet",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/tablet/tablet1.png',
    name: 'Amazon Fire HD 10',
    price: 952.88,
    rate: 4.0,
    distance: 793,

Раба, [08.04.2025 15:02]
description: "Бюджетный планшет для просмотра видео, чтения и серфинга в интернете.",
    category: "Tablet",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/watch/watch1.png',
    name: 'Apple Watch Ultra',
    price: 836.06,
    rate: 4.9,
    distance: 896,
    description: "Умные часы для экстремалов с улучшенной прочностью и длительным временем работы.",
    category: "Watch",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/watch/watch1.png',
    name: 'Samsung Galaxy Watch 6',
    price: 2015.96,
    rate: 3.8,
    distance: 829,
    description: "Смарт-часы с широкими возможностями фитнес-отслеживания и интеграцией с Android.",
    category: "Watch",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/watch/watch1.png',
    name: 'Garmin Fenix 7',
    price: 1876.00,
    rate: 4.2,
    distance: 133,
    description: "Профессиональные спортивные часы с GPS, пульсометром и автономной работой до 18 дней.",
    category: "Watch",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/watch/watch1.png',
    name: 'Fitbit Versa 4',
    price: 2027.74,
    rate: 4.5,
    distance: 716,
    description: "Фитнес-часы с мониторингом сна, пульса и встроенным GPS.",
    category: "Watch",
  ),
  MyProductModel(
    image: 'food-delivery(foodel)/watch/watch1.png',
    name: 'Huawei Watch GT 4',
    price: 750.37,
    rate: 4.7,
    distance: 549,
    description: "Умные часы с классическим дизайном, высокой автономностью и функциями здоровья.",
    category: "Watch",
  ),
];